/**
 * Check if an array has elements
 * @param arr array to check
 * @returns 
 */
export const HasElements = (arr: object | undefined | null): boolean => {
  return !!arr && Object.keys(arr).length > 0;
};

/**
 * Removes duplicate elements from an array based on a key generated by the provided callback function.
 * @param arr - The array from which to remove duplicates.
 * @param keyGenerator - A callback function that generates a unique key for each element.
 * @returns A new array with unique elements.
 */
export const UniqueArray = <T>(arr: T[], keyGenerator: (element: T) => string = (element) => element as string): T[] => {
  const uniqueElements: { [key: string]: T } = {};

  arr.forEach((element) => {
    const key = keyGenerator(element);
    uniqueElements[key] = element;
  });

  return Object.keys(uniqueElements).map((key) => uniqueElements[key]);
};
